[tool.poetry]
name = "checkstatus"
version = "0.1.0"
description = ""
authors = ["Court Schuett <schuettc@amazon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sagemaker = "^2.145.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
